### ISSUE TITLE
Where is the repo of Hey Siri =P?

### ISSUE THREAD

**Issue by MrWillCom** [quietshu/labs#1]
Where is the repo of [Hey Siri =P](https://quietshu.github.io/labs/hey-siri/)? I can't find it in [quietshu/labs](https://github.com/quietshu/labs).

**Comment by shuding** [comment]
Hi @MrWillCom it's under another branch: https://github.com/shuding/labs/tree/gh-pages

**Comment by MrWillCom** [comment]
And what license does it base on? or it's not open source?

**Comment by shuding** [comment]
@MrWillCom open sourced under the MIT license.

**Comment by MrWillCom** [comment]
Okay! Thank you.
